services:
  ollamaintegrationapi:
    build:
      context: .
      dockerfile: OllamaIntegrationAPI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - llamacpp
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./tessdata:/app/tessdata

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_models:/root/.ollama
  #   restart: unless-stopped

  llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server
    ports:
      - "11220:11220"
    volumes:
      - "./models:/models"
    environment:
      LLAMA_ARG_MODEL: "/models/Qwen2.5-VL-7B-Instruct-q4_k_m.gguf"
      LLAMA_ARG_MMPROJ: "/models/mmproj-BF16.gguf"
      LLAMA_ARG_CTX_SIZE: "22110"
      LLAMA_ARG_HOST: "0.0.0.0"
      LLAMA_ARG_PORT: "11220"
      # AUTO GPU detection o override:
      LLAMA_ARG_N_GPU_LAYERS: "0"
    # Si pones GPU later:
    # gpus: "all"